# Generated by Django 5.0.1 on 2024-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduce',
            field=models.TextField(default='나를 소개합니다.', max_length=300),
        ),
    ]
