# Generated by Django 5.0.1 on 2024-01-10 14:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='image/%Y/%m'),
        ),
    ]
